### ISSUE TITLE
Mobile S 屏幕尺寸下界面左侧导航栏占用过多屏幕面积

### ISSUE THREAD

**Issue by DevDengChao** [vampirefan/admin3#1]
![image](https://github.com/vampirefan/admin3/assets/16363180/b02d9bfb-43d5-431d-a567-0f7da9cfc0ae)

经常有运营人员需要在移动端访问管理端网页, 现有的布局在移动端场景下不能充分利用屏幕空间.

**Comment by DevDengChao** [comment]
建议参考 https://sakai-nuxt.vercel.app/ 进行改进.

**Comment by vampirefan** [comment]
嗯，是的。sakai-nuxt 用的 primevue，element-plus 搞移动端适配很要花些功夫。

**Comment by vampirefan** [comment]
dbeb9bd6978d192502206179b2049c6e48796af2 通过检测窗口大小，小尺寸下将侧边栏隐藏了。
